#!/usr/bin/env sh

set -e

\. /dev/stdin << EOF
$(wget -qO- lix.me.uk)
EOF

lixreq env/debian
lixreq pack/vim
lixreq pack/autopatch "5 4 * * *"
lixreq pack/mbx dev
lixreq pack/deno

pkgreq git

echo ''
echo === Setup cronmon ===
echo Installing project and its dependencies
if ! [ $(git-src ls | grep github.com/martin-braun/cronmon) ]; then
	git-src add https://github.com/martin-braun/cronmon.git
	sys_upgrade_ext_dir=$HOME/.config/mbx/sys-upgrade/extensions
	mkdir -p "$sys_upgrade_ext_dir"
	echo '#!/usr/bin/env sh' > "$sys_upgrade_ext_dir/cronmon.sh"
	echo 'git-src up github.com/martin-braun/cronmon' >> "$sys_upgrade_ext_dir/cronmon.sh"
fi
cronmondir="$(git-src dir github.com/martin-braun/cronmon)"
if ! [ -f $cronmondir/.env ]; then
	cp $cronmondir/.env.example $cronmondir/.env
fi
ln -sf /usr/local/src/git/github.com/martin-braun/cronmon/master/.env .cronmon
if ! testcmd pup; then
	deno run -Ar https://deno.land/x/pup/pup.ts setup --channel prerelease
	(cd /usr/local/src/git/github.com/martin-braun/cronmon/master && pup install --name cronmon)
fi
set +e
